spring.config.use-legacy-processing=true

server.port=8282
spring.application.name=simple

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=Q2F1c2FsSXNJVEFTZXJ2ZXJTYW1wbGVTZWNyZXRLZXk=
jwt.expiration=1200000

spring.h2.console.enabled=true

spring.datasource.jdbc-url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always
spring.datasource.initialization-mode=always
spring.datasource.generate-unique-name=false
spring.datasource.hikari.maximum-pool-size=4

# Read DB
spring.datasource.read.jdbc-url=jdbc:h2:mem:testdb
# spring.datasource.read.driver-class-name=org.h2.Driver
spring.datasource.read.username=sa
spring.datasource.read.password=

# Write DB
spring.datasource.write.jdbc-url=jdbc:h2:mem:testdb
# spring.datasource.write.driver-class-name=org.h2.Driver
spring.datasource.write.username=sa
spring.datasource.write.password=

mybatis.mapper-locations: mapper/**/*.xml
# mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.cube.simple.model

logging.level.com.cube.simple.mapper=TRACE
