DROP TABLE IF EXISTS Demo;
CREATE TABLE Demo (
	id IDENTITY PRIMARY KEY
	, name VARCHAR (255) NOT NULL
	, image VARCHAR (255) NOT NULL
	, description VARCHAR (255)
);
DROP TABLE IF EXISTS Item;
CREATE TABLE Item (
	id IDENTITY PRIMARY KEY
	, price BIGINT NOT NULL
	, name VARCHAR (255) NOT NULL
	, image VARCHAR (255) NOT NULL
	, description VARCHAR (255)
);
