jdbc.driverClass=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://jejuyeora-test-db-server.cpkumwc0ac2a.ap-northeast-2.rds.amazonaws.com:27836/jejuyeora?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useInformationSchema=true
jdbc.user=[develop db username here]
jdbc.password=[develop db password here]

gen.java.dir=target
gen.resources.dir=target
